version: '3.4'

services:
  someservice:
    build:
      context: ./
  
  someotherservice:
    image:  domano/memefy_frontend:latest
  buildwatch:
    build:
      context: ../
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "$PWD:/app/base/"